---
- name: Collect basic info
  hosts: all
  gather_facts: false

  tasks:
    - name: Whoami
      ansible.builtin.command: whoami
      register: whoami_out
    - debug:
        var: whoami_out.stdout

    - name: Hostname
      ansible.builtin.command: hostname
      register: hostname_out
    - debug:
        var: hostname_out.stdout

    - name: Uptime
      ansible.builtin.command: uptime
      register: uptime_out
    - debug:
        var: uptime_out.stdout

    - name: NTP client status
      ansible.builtin.command: timedatectl status
      register: ntp_out
    - debug:
        var: ntp_out.stdout
