- name: Collect facts
  hosts: all
  gather_facts: true

  tasks:
    - debug:
        msg:
          - "OS = {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Kernel = {{ ansible_kernel }}"
          - "SSH user = {{ ansible_user }}"
